# Generated by Django 4.1.5 on 2023-12-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="tablaRamos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PERIODO", models.IntegerField()),
                ("PLAN_DE_ESTUDIOS", models.CharField(max_length=100)),
                ("ESCUELA", models.CharField(max_length=100)),
                ("NRC", models.IntegerField()),
                (
                    "CONECTOR_LIGA",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "LISTA_CRUZADA",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("MATERIA", models.CharField(max_length=100)),
                ("CURSO", models.IntegerField()),
                ("SECCION", models.CharField(max_length=10)),
                ("TITULO", models.CharField(max_length=100)),
                ("CREDITO", models.IntegerField()),
                ("LUNES", models.CharField(blank=True, max_length=100, null=True)),
                ("MARTES", models.CharField(blank=True, max_length=100, null=True)),
                ("MIERCOLES", models.CharField(blank=True, max_length=100, null=True)),
                ("JUEVES", models.CharField(blank=True, max_length=100, null=True)),
                ("VIERNES", models.CharField(blank=True, max_length=100, null=True)),
                ("SABADO", models.CharField(blank=True, max_length=100, null=True)),
                ("DOMINGO", models.CharField(blank=True, max_length=100, null=True)),
                ("INICIO", models.DateTimeField(auto_now_add=True, null=True)),
                ("FIN", models.DateTimeField(auto_now_add=True, null=True)),
                ("TIPO", models.CharField(max_length=10)),
                ("PROFESOR", models.CharField(blank=True, max_length=100, null=True)),
                ("SALA", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
