# Generated by Django 4.1.5 on 2023-12-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toma_de_ramos_app", "0004_alter_tablaramos_seccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablaramos",
            name="FIN",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="tablaramos",
            name="INICIO",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
